version: '3'
services:
  web:
    image: akwiatkowskii/api-performance-test-app
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URI=mysql://user:password@db:3306/database_name
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'database_name'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

